FROM nginx:stable-alpine

# add user for php-fpm
RUN adduser -u 82 -D -H -G www-data www-data

# setup nginx config
COPY resources/docker/etc-nginx.conf /etc/nginx/nginx.conf
COPY resources/docker/nginx.conf /etc/nginx/conf.d/default.conf

# add horaro
WORKDIR /var/www/horaro
COPY --from=horaro-builder /build .

USER www-data
